# Generated by Django 4.1.2 on 2023-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.IntegerField()),
                ('diet', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('larvae_weight', models.FloatField()),
                ('before_dry', models.FloatField()),
                ('after_dry', models.FloatField()),
            ],
        ),
    ]
